### ISSUE TITLE
HM 12.8.1.2

### ISSUE THREAD

**Issue by mierswa** [aerohive/devices-details-to-csv#1]
doesn´t work on HM 12.8.1.2.

node devices.js > test.csv
REQUEST QUERY: /xapi/v1/monitor/devices?ownerId=2&page=0
REQUEST HEADERS:{"X-AH-API-CLIENT-SECRET":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","X-AH-API-CLIENT-ID":"myid","X-AH-API-CLIENT-REDIRECT-URI":"https://127.0.0.1","Authorization":"Bearer mytokenxxxxx"}
REQUEST STATUS: 200
RESPONSE DATA: {"data":[{"deviceid":8589940160,<and more DATA>
to here all works fine
REQUEST QUERY: /xapi/v1/monitor/devices/8589940032?ownerId=2
REQUEST HEADERS:{"X-AH-API-CLIENT-SECRET":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","X-AH-API-CLIENT-ID":"myid","X-AH-API-CLIENT-REDIRECT-URI":"https://127.0.0.1","Authorization":"Bearer mytokenxxxxxx"}
REQUEST STATUS: 500
RESPONSE DATA:<html>
<head><title>500 Internal Server Error</title></head>
 <body bgcolor="white">
 <center><h1>500 Internal Server Error</h1></center>
 <hr><center>nginx</center>
</body>
</html>
 
undefined:1
<html>
^
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (C:\Users\sven\Documents\HMNG_tools\details\devices.js:155:29)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

please help thanks

**Comment by tmunzer** [comment]
Hi mierswa,

I just tried on my side this script against a NGVA in 12.8.1.2, and I don't have any issue.
From what I understand, NGVA is returning this error when the script is trying to get information about the device 8589940032. Can you let me know which kind of device it is?

Thanks,
Thomas

**Comment by mierswa** [comment]
Hello tmunzer,
the device is an AP_250 (if you need more information, just ask) I have no problems with the script "devices-to-csv", only the devices-details-to-csv script causes my hivemanager NG to crash. In the Hivemanager itself I can look at the detailed view of the access point.
Best regards
Mierswa

**Comment by tmunzer** [comment]
thanks. Can you try to manually generate this request with Postman. It's not a script issue (form the logs, the script is generating the right request, but NG is responding with a HTTP500).
If you get the same answer with Postman, you may have to open a support case.

**Comment by mierswa** [comment]
Hello tmunzer,
i have done this test without errors with postman. but there is a difference in the result. I get an attribute more with Postman ("activeClients": 0, "). In the script that causes the hivemanager to crash, there is no such attribute. Can this possibly be the error?
Best regards
Mierswa

**Comment by tmunzer** [comment]
Mierswa,

Can you send me the whole logs from the script by email (you'll find my corporate email address in my github profile)?

Thanks,
Tohmas
